variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: none

## CI Stages:
#    manual: Manual jobs used to do CI maintainance, like wiping the directory or clearing cache
#    prep  : Jobs to ensure the repo is up to date with tools, prog and ucode
#    check : Sanity checks of RTL quality
#    test-short :
#    test-medium:
#    test-long  : Functional RTL tests
stages:
  - manual
  - check
  - test-short
  - test-medium
  - test-long
  - test-ultralong

.job_template: &job_definition
  only:
    - master
    - dev
    - fe_dev
    - be_dev
    - me_dev
    - top_dev
    - sw_dev
  before_script:
    - echo "Making libs"
    - make -C rtl libs
    - cd $CI_PROJECT_DIR/rtl
  artifacts:
    when: always
    paths:
      - "rtl/bp_fe/syn/reports/"
      - "rtl/bp_be/syn/reports/"
      - "rtl/bp_me/syn/reports/"
      - "rtl/bp_top/syn/reports/"
      - "rtl/bp_fe/syn/logs/"
      - "rtl/bp_be/syn/logs/"
      - "rtl/bp_me/syn/logs/"
      - "rtl/bp_top/syn/logs/"
#  cache: &global_cache
#    key: $CI_COMMIT_REF_SLUG
#    paths:
#      - $CI_PROJECT_DIR/sdk
#    policy: pull
  dependencies: []
  retry:
    max: 3
    when:
      - script_failure

check-design:
  <<: *job_definition
  stage: check
  tags:
    - dc
  script:
    - $CI_PROJECT_DIR/rtl/ci/check_design.sh $CI_CORES

# Some licensing issue as of 02/10/21
synth-vivado:
  <<: *job_definition
  stage: check
  allow_failure: true
  tags:
    - vivado
  script:
    - $CI_PROJECT_DIR/rtl/ci/synth_vivado.sh $CI_CORES

lint-verilator:
  <<: *job_definition
  stage: check
  tags:
    - verilator
  script:
    - $CI_PROJECT_DIR/rtl/ci/lint.sh verilator $CI_CORES

lint-vcs:
  <<: *job_definition
  stage: check
  tags:
    - vcs
  script:
    - $CI_PROJECT_DIR/rtl/ci/lint.sh vcs $CI_CORES

tire_kick:
  <<: *job_definition
  stage: check
  tags:
    - verilator
  script:
    - $CI_PROJECT_DIR/rtl/ci/tire_kick.sh $CI_CORES

bloodgraph-vcs:
  <<: *job_definition
  stage: test-short
  tags:
    - vcs
  script:
    - $CI_PROJECT_DIR/rtl/ci/bloodgraph.sh $CI_CORES

weird-verilator:
  <<: *job_definition
  when: manual
  stage: test-short
  tags:
    - verilator
  script:
    - $CI_PROJECT_DIR/rtl/ci/weird_config.sh verilator $CI_CORES

weird-vcs:
  <<: *job_definition
  stage: test-short
  tags:
    - vcs
  script:
    - $CI_PROJECT_DIR/rtl/ci/weird_config.sh vcs $CI_CORES

l2e-vcs:
  <<: *job_definition
  stage: test-medium
  tags:
    - vcs
  script:
    - $CI_PROJECT_DIR/rtl/ci/l2e_config.sh vcs $CI_CORES

l2e-verilator:
  <<: *job_definition
  when: manual
  stage: test-medium
  tags:
    - verilator
  script:
    - $CI_PROJECT_DIR/rtl/ci/l2e_config.sh verilator $CI_CORES

me-regress-verilator:
  <<: *job_definition
  when: manual
  stage: test-short
  tags:
    - verilator
  script:
    - $CI_PROJECT_DIR/rtl/ci/me_regress.sh verilator $CI_CORES

me-regress-vcs:
  <<: *job_definition
  stage: test-short
  tags:
    - vcs
  script:
    - $CI_PROJECT_DIR/rtl/ci/me_regress.sh vcs $CI_CORES

top-bootrom-verilator:
  <<: *job_definition
  stage: test-short
  tags:
    - verilator
  script:
    - $CI_PROJECT_DIR/rtl/ci/bootrom.sh verilator $CI_CORES

top-bootrom-vcs:
  <<: *job_definition
  stage: test-short
  tags:
    - vcs
  script:
    - $CI_PROJECT_DIR/rtl/ci/bootrom.sh vcs $CI_CORES

top-riscv-tests-verilator:
  <<: *job_definition
  stage: test-short
  tags:
    - verilator
  script:
    - $CI_PROJECT_DIR/rtl/ci/single_core_testlist.sh verilator RISCV_TESTLIST $CI_CORES

top-riscv-tests-vcs:
  <<: *job_definition
  stage: test-short
  tags:
    - vcs
  script:
    - $CI_PROJECT_DIR/rtl/ci/single_core_testlist.sh vcs RISCV_TESTLIST $CI_CORES

top-amo-tests-verilator:
  <<: *job_definition
  when: manual
  stage: test-short
  tags:
    - verilator
  script:
    - $CI_PROJECT_DIR/rtl/ci/single_core_atomics.sh verilator $CI_CORES

top-amo-tests-vcs:
  <<: *job_definition
  stage: test-short
  tags:
    - vcs
  script:
    - $CI_PROJECT_DIR/rtl/ci/single_core_atomics.sh vcs $CI_CORES

dcache-vcs:
  <<: *job_definition
  stage: test-short
  tags:
    - vcs
  script:
    - $CI_PROJECT_DIR/rtl/ci/dcache_regress.sh vcs $CI_CORES

icache-vcs:
  <<: *job_definition
  stage: test-short
  tags:
    - vcs
  script:
    - $CI_PROJECT_DIR/rtl/ci/icache_regress.sh vcs $CI_CORES

top-mc-verilator:
  <<: *job_definition
  stage: test-medium
  tags:
    - verilator
  script:
    - $CI_PROJECT_DIR/rtl/ci/multicore.sh verilator $CI_CORES

top-mc-vcs:
  <<: *job_definition
  stage: test-medium
  tags:
    - vcs
  script:
    - $CI_PROJECT_DIR/rtl/ci/multicore.sh vcs $CI_CORES

top-misc-vcs:
  <<: *job_definition
  stage: test-medium
  tags:
    - vcs
  script:
    - $CI_PROJECT_DIR/rtl/ci/single_core_testlist.sh vcs MISC_TESTLIST $CI_CORES

top-misc-verilator:
  <<: *job_definition
  when: manual
  stage: test-medium
  tags:
    - verilator
  script:
    - $CI_PROJECT_DIR/rtl/ci/single_core_testlist.sh verilator MISC_TESTLIST $CI_CORES

top-riscvdv-vcs:
  <<: *job_definition
  when: manual
  stage: test-medium
  tags:
    - vcs
  script:
    - $CI_PROJECT_DIR/rtl/ci/single_core_testlist.sh vcs RISCVDV_TESTLIST $CI_CORES

# Verilator 4.104 "internal error"
top-checkpoint-verilator:
  <<: *job_definition
  when: manual
  stage: test-medium
  tags:
    - verilator
  script:
    - $CI_PROJECT_DIR/rtl/ci/checkpoint.sh verilator $CI_CORES

top-checkpoint-vcs:
  <<: *job_definition
  stage: test-medium
  tags:
    - vcs
  script:
    - $CI_PROJECT_DIR/rtl/ci/checkpoint.sh vcs $CI_CORES

check-loops:
  <<: *job_definition
  stage: test-medium
  tags:
    - dc
  script:
    - $CI_PROJECT_DIR/rtl/ci/check_loops.sh $CI_CORES

# Pending https://github.com/bespoke-silicon-group/basejump_stl/pull/387/
top-dram-vcs:
  <<: *job_definition
  when: manual
  stage: test-medium
  tags:
    - vcs
  script:
    - $CI_PROJECT_DIR/rtl/ci/dram.sh

top-linux-verilator:
  <<: *job_definition
  when: manual
  stage: test-ultralong
  tags:
    - verilator
  script:
    $CI_PROJECT_DIR/rtl/ci/linux.sh verilator $CI_CORES

top-coremark-verilator:
  <<: *job_definition
  when: manual
  stage: test-long
  tags:
    - verilator
  script:
    - $CI_PROJECT_DIR/rtl/ci/single_core_testlist.sh verilator COREMARK_TESTLIST $CI_CORES

top-coremark-vcs:
  <<: *job_definition
  stage: test-long
  tags:
    - vcs
  script:
    - $CI_PROJECT_DIR/rtl/ci/single_core_testlist.sh vcs COREMARK_TESTLIST $CI_CORES

top-beebs-verilator:
  <<: *job_definition
  when: manual
  stage: test-long
  tags:
    - verilator
  script:
    - $CI_PROJECT_DIR/rtl/ci/single_core_testlist.sh verilator BEEBS_TESTLIST $CI_CORES

top-beebs-vcs:
  <<: *job_definition
  stage: test-long
  tags:
    - vcs
  script:
    - $CI_PROJECT_DIR/rtl/ci/single_core_testlist.sh vcs BEEBS_TESTLIST $CI_CORES

top-linux-vcs:
  <<: *job_definition
  when: manual
  stage: test-ultralong
  tags:
    - vcs
  script:
    $CI_PROJECT_DIR/rtl/ci/linux.sh vcs $CI_CORES

